public/index.html
I changed the title just to check if git push works properly. If necessary, we'll change it to a better title later.
=> website title changed

src/core/App/theme.js, src/features/MoviesList/styled.js
the size of the gap between the rows were to big and responsiveness for mobiles didn't work properly. I fixed it.
=> gap size fixed and responsiveness for mobile fixed

src/assets/camera.svg, src/assets/search.svg, src/common/Navigation/Search/index.js, src/common/Navigation/Search/styled.js, src/common/Navigation/index.js, src/common/Navigation/styled.js, src/core/App/App.js, src/core/App/index.js, src/core/App/routes.js
I have added basic styling to navigation and search engine, routers, and the proposed look to app.js
=> Navigation basic

src/core/App/theme.js, src/features/MoviesList/styled.js
box-shadow color name to the theme, transition with 105% scale and d…arker box-shadow added
=> small changes in Movie Tile

src/common/MovieTile/index.js, src/common/MovieTile/styled.js, src/features/MoviesList/getPopularMovies.js, src/features/MoviesList/index.js
Now Posters and year of release date are working with api
=> Api poster and year

src/common/MovieTile/index.js, src/common/MovieTile/styled.js, src/features/MoviesList/index.js
I have cleand up after last marge and add api to MovieTile instead of MoviesList
=> Api to movie tile

src/common/Navigation/Search/styled.js
=> searchbox mobile vision fixed

src/core/store.js, src/features/PeopleList/popularPeopleSaga.js, src/features/PeopleList/popularPeopleSlice.js
Added {payload} to PeopleSlice , because our app crushed
=> repair app,added payload do peopleSlice

src/core/rootSaga.js, src/features/PeopleList/getPopularPeople.js, src/features/PeopleList/index.js, src/features/PeopleList/popularPeopleSlice.js
I've added to rootSaga popularPeopleSaga and fixed people showing up in navigation.
=> added to rootSaga peopleSaga, and reapair people

src/common/MainHeader/index.js, src/common/MainHeader/styled.js, src/common/MovieTile/styled.js, src/common/PersonTile/index.js, src/common/PersonTile/styled.js, src/features/MoviesList/index.js, src/features/PeopleList/index.js, src/features/PeopleList/styled.js
Now people page is working. You can see popular people from api and it is styled.
=> People list css and api

src/common/PersonTile/styled.js, src/features/PeopleList/index.js, src/features/PeopleList/styled.js
I have adjusted mobile view form people page
=> mobile responisivnes fixed for people page

src/common/Navigation/Search/index.js, src/common/Navigation/Search/styled.js, src/common/Navigation/styled.js, src/features/queryParameters.js, src/features/searchQueryParamName.js, src/queryParameters.js, src/searchQueryParamName.js
=> Search engine1

src/common/MovieTile/index.js
I have added .toFixed(1) to rate of votes , so now you can see score 7.0 instead of 7.
=> vote score updated to .0

src/common/Loading/index.js, src/common/Loading/spinner.svg, src/common/Loading/styled.js, src/core/App/theme.js
=> Loading spinner added

src/common/Navigation/Search/styled.js, src/common/Navigation/index.js, src/common/Navigation/styled.js
i fixed responsive  search,  check it
=> responsive fixed

src/features/people/PersonPage/index.js, src/features/people/PersonPage/personSlice.js, src/features/people/PersonPage/styled.js
I have added crew and cast to the person page
=> Person crew cast

src/common/PersonTile/index.js, src/common/PersonTile/styled.js, src/features/movies/MovieDetails/index.js, src/features/movies/MovieDetails/styled.js, src/features/people/PersonPage/personSlice.js
I've added cast and crew to movie details and now is showing
=> Cast and crew in movie details

src/common/Navigation/Search/getSearch.js
=> repaired search

src/common/Navigation/Search/getSearch.js, src/features/people/PeopleList/getPopularPeople.js, src/features/people/PeopleList/index.js, src/features/people/PeopleList/popularPeopleSaga.js, src/features/people/PeopleList/popularPeopleSlice.js
Changed slice and saga to similar like PopularMoviesList, and added search people and pagination.
=> Search people working

src/common/MainHeader/styled.js, src/common/NoResult/index.js, src/common/NoResult/styled.js, src/features/movies/MoviesList/index.js
=> No results page

src/common/PersonTile/index.js, src/features/movies/MovieDetails/index.js, src/features/people/PeopleList/index.js
Thanks to Aneta, after some minor corrections it works now. After clicking on the cast in movie details it goes to people.
=> PeopleTiles working

src/common/PersonTile/index.js, src/common/PersonTile/styled.js
Deleted not working PersonTiles and added color to tile.
=> PersonTiles styled

src/common/ErrorPage/index.js, src/common/ErrorPage/styled.js
=> ErrorPage fixed visible
